config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :room_categories
  resources :devices
  resources :categories
  resources :rooms
  get 'main/index'
  root 'main#index'

end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :room_category
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :type, :on, :room_category_id)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for @device, :html => { :class => "form-horizontal device" } do |f| %>

  <% if @device.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @device.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :type, :class => 'form-control' %>
    </div>
    <%=f.error_span(:type) %>
  </div>
  <div class="form-group">
    <%= f.label :on, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :on, :class => 'form-control' %>
    </div>
    <%=f.error_span(:on) %>
  </div>
  <div class="form-group">
    <%= f.label :room_category_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :room_category_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:room_category_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                devices_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/devices/edit.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/index.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:on) %></th>
      <th><%= model_class.human_attribute_name(:room_category_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= link_to device.id, device_path(device) %></td>
        <td><%= device.name %></td>
        <td><%= device.type %></td>
        <td><%= device.on %></td>
        <td><%= device.room_category_id %></td>
        <td><%=l device.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_device_path(device), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      device_path(device),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_device_path,
            :class => 'btn btn-primary' %>

app/views/devices/new.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/show.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @device.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @device.type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:on) %>:</strong></dt>
  <dd><%= @device.on %></dd>
  <dt><strong><%= model_class.human_attribute_name(:room_category_id) %>:</strong></dt>
  <dd><%= @device.room_category_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              devices_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_device_path(@device), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              device_path(@device),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>