config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :room_categories
  resources :devices
  resources :categories
  resources :rooms
  get 'main/index'
  root 'main#index'

end

app/models/room_category.rb
class RoomCategory < ActiveRecord::Base
end

app/controllers/room_categories_controller.rb
class RoomCategoriesController < ApplicationController
  before_action :set_room_category, only: [:show, :edit, :update, :destroy]

  # GET /room_categories
  # GET /room_categories.json
  def index
    @room_categories = RoomCategory.all
  end

  # GET /room_categories/1
  # GET /room_categories/1.json
  def show
  end

  # GET /room_categories/new
  def new
    @room_category = RoomCategory.new
  end

  # GET /room_categories/1/edit
  def edit
  end

  # POST /room_categories
  # POST /room_categories.json
  def create
    @room_category = RoomCategory.new(room_category_params)

    respond_to do |format|
      if @room_category.save
        format.html { redirect_to @room_category, notice: 'Room category was successfully created.' }
        format.json { render :show, status: :created, location: @room_category }
      else
        format.html { render :new }
        format.json { render json: @room_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /room_categories/1
  # PATCH/PUT /room_categories/1.json
  def update
    respond_to do |format|
      if @room_category.update(room_category_params)
        format.html { redirect_to @room_category, notice: 'Room category was successfully updated.' }
        format.json { render :show, status: :ok, location: @room_category }
      else
        format.html { render :edit }
        format.json { render json: @room_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /room_categories/1
  # DELETE /room_categories/1.json
  def destroy
    @room_category.destroy
    respond_to do |format|
      format.html { redirect_to room_categories_url, notice: 'Room category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room_category
      @room_category = RoomCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_category_params
      params.require(:room_category).permit(:name, :room_id, :category_id)
    end
end

app/helpers/room_categories_helper.rb
module RoomCategoriesHelper
end

app/views/room_categories/_form.html.erb
<%= form_for @room_category, :html => { :class => "form-horizontal room_category" } do |f| %>

  <% if @room_category.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@room_category.errors.count, "error") %> prohibited this room_category from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @room_category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :room_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :room_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:room_id) %>
  </div>
  <div class="form-group">
    <%= f.label :category_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :category_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:category_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                room_categories_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/room_categories/edit.html.erb
<%- model_class = RoomCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/room_categories/index.html.erb
<%- model_class = RoomCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:room_id) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @room_categories.each do |room_category| %>
      <tr>
        <td><%= link_to room_category.id, room_category_path(room_category) %></td>
        <td><%= room_category.name %></td>
        <td><%= room_category.room_id %></td>
        <td><%= room_category.category_id %></td>
        <td><%=l room_category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_room_category_path(room_category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      room_category_path(room_category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_room_category_path,
            :class => 'btn btn-primary' %>

app/views/room_categories/new.html.erb
<%- model_class = RoomCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/room_categories/show.html.erb
<%- model_class = RoomCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @room_category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:room_id) %>:</strong></dt>
  <dd><%= @room_category.room_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @room_category.category_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              room_categories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_room_category_path(@room_category), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              room_category_path(@room_category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>